In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import cv2
print(tf.__version__)

2.7.0


In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

len(x_train) # 60000

len(x_test) # 10000

x_train[0].shape 

(28, 28)

In [3]:
x_train = x_train / 255
x_test = x_test / 255

In [4]:
x_train_flattened = x_train.reshape(len(x_train), 28*28)
x_test_flattened = x_test.reshape(len(x_test), 28*28)

In [9]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape=(784,), activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])


model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(x_train_flattened, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2731 - accuracy: 0.9229
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1214 - accuracy: 0.9635
Epoch 3/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0850 - accuracy: 0.9742
Epoch 4/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0646 - accuracy: 0.9804
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0514 - accuracy: 0.9845


In [10]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0761 - accuracy: 0.9781


[0.07612281292676926, 0.9781000018119812]

# Rank-1 accuracy

In [88]:
def custom_image(img_path):
    img_path = "C:/Users/ASUS TUF/Desktop/Quick Access/dl/  /" + img_path
    img2 = cv2.imread(img_path, 0)

    img2 = img2 / 255
    img2 = img2.reshape(1, 28*28)
    
    img2Y = model.predict(img2)
    img2_result = np.argmax(img2Y)
    print("Result -> ", img2_result, end = "\t")

    img2Y = img2Y.reshape(10)
    scce = tf.keras.losses.SparseCategoricalCrossentropy()
    print("Loss:",scce(img2_result, img2Y).numpy())
    return img2_result

In [89]:
acc = 0
for xx in range(0, 10):
  print("---The tested number: ", xx)

  test1 = custom_image(f't{xx}.png')
  if(test1 == xx) : acc+=1

  test2 = custom_image(f't{xx}-2.png')
  if(test2 == xx) : acc+=1
  
  test3 = custom_image(f't{xx}-3.png')
  if(test3 == xx) : acc+=1

  print()

---The tested number:  0
Result ->  6	Loss: 1.4458361
Result ->  9	Loss: 1.6284527
Result ->  3	Loss: 1.291334

---The tested number:  1
Result ->  1	Loss: 1.3230598
Result ->  5	Loss: 1.6302848
Result ->  3	Loss: 1.0377642

---The tested number:  2
Result ->  2	Loss: 0.9755621
Result ->  2	Loss: 1.2708485
Result ->  3	Loss: 0.83873045

---The tested number:  3
Result ->  2	Loss: 1.3318615
Result ->  2	Loss: 0.69384444
Result ->  3	Loss: 1.483598

---The tested number:  4
Result ->  4	Loss: 1.3906215
Result ->  4	Loss: 1.088283
Result ->  7	Loss: 1.1328514

---The tested number:  5
Result ->  2	Loss: 1.366093
Result ->  5	Loss: 1.0800189
Result ->  3	Loss: 1.1656868

---The tested number:  6
Result ->  6	Loss: 1.3479868
Result ->  8	Loss: 1.2191948
Result ->  7	Loss: 0.9560714

---The tested number:  7
Result ->  7	Loss: 1.2732733
Result ->  2	Loss: 1.1169707
Result ->  3	Loss: 1.0980316

---The tested number:  8
Result ->  3	Loss: 1.2353864
Result ->  4	Loss: 1.6284305
Result ->  7	Lo

In [90]:
print('The accuracy is:', int(acc/0.3), '%')

The accuracy is: 30 %


# Rank-5 accuracy

In [1]:
from numpy import array
from numpy import argsort
argsort(array([1, 3, 2, 4]))[::-1]

array([3, 1, 2, 0], dtype=int64)

In [2]:
argsort([2, 3, 1])  # 1 2 3

array([2, 0, 1], dtype=int64)

In [4]:
array([2, 3, 1])[argsort([2, 3, 1])]

array([1, 2, 3])

In [91]:
def custom_image(img_path):
    img_path = "C:/Users/ASUS TUF/Desktop/Quick Access/dl/custom handwritings/" + img_path
    img2 = cv2.imread(img_path, 0)

    img2 = img2 / 255
    img2 = img2.reshape(1, 28*28)
    
    img2Y = model.predict(img2)
    img2_result = np.argsort(img2Y).reshape(-1)[:-6:-1]
    
    print("\tResult -> ", img2_result, end = "\t")

    img2Y = img2Y.reshape(10)
    return img2_result

In [92]:
acc2 = 0
for xx in range(0, 10):
  print("---The tested number: ", xx, end= "")

  test1 = custom_image(f't{xx}.png')
  if(xx in test1) : acc2+=1

  test2 = custom_image(f't{xx}-2.png')
  if(xx in test1) : acc2+=1
  
  test3 = custom_image(f't{xx}-3.png')
  if(xx in test1) : acc2+=1

  print("\n")

---The tested number:  0	Result ->  [6 0 4 3 7]		Result ->  [9 7 2 0 5]		Result ->  [3 7 8 2 5]	

---The tested number:  1	Result ->  [1 7 2 4 5]		Result ->  [5 8 6 4 1]		Result ->  [3 7 8 2 6]	

---The tested number:  2	Result ->  [2 1 5 8 6]		Result ->  [2 3 1 8 6]		Result ->  [3 7 2 8 5]	

---The tested number:  3	Result ->  [2 6 3 5 1]		Result ->  [2 3 8 1 4]		Result ->  [3 7 8 2 6]	

---The tested number:  4	Result ->  [4 8 9 3 7]		Result ->  [4 7 8 2 9]		Result ->  [7 3 8 2 9]	

---The tested number:  5	Result ->  [2 8 5 3 6]		Result ->  [5 1 6 3 8]		Result ->  [3 7 8 2 6]	

---The tested number:  6	Result ->  [6 8 5 0 7]		Result ->  [8 5 6 2 9]		Result ->  [7 3 2 8 5]	

---The tested number:  7	Result ->  [7 3 2 1 8]		Result ->  [2 1 8 3 4]		Result ->  [3 7 8 2 5]	

---The tested number:  8	Result ->  [3 2 5 8 6]		Result ->  [4 6 7 2 3]		Result ->  [7 3 2 8 6]	

---The tested number:  9	Result ->  [1 6 7 2 3]		Result ->  [2 3 1 7 9]		Result ->  [3 7 2 8 5]	



In [94]:
print('The accuracy is:', int(acc2/0.3), '%')

The accuracy is: 90 %


In [101]:
print(f'True positives:\t\tRank-1: {acc}\tRank-5: {acc2}')
print(f'Accuracy:\t\tRank-1: {int(acc/0.3)}%\tRank-5: {int(acc2/0.3)}%')

True positives:		Rank-1: 9	Rank-5: 27
Accuracy:		Rank-1: 30%	Rank-5: 90%
